// Generated by scripts/generate-file-icons.py. Edit shared/file-icons/catalog.json.
package com.bluelink.android.ui.content

import androidx.compose.ui.graphics.Color
import com.bluelink.android.R

internal data class FileTypeAsset(val drawable: Int, val light: Color, val dark: Color)
internal val fileTypeAssets = mapOf(
    "file-pdf-symbol" to FileTypeAsset(R.drawable.file_type_file_pdf_symbol, Color(0xFFD92D20), Color(0xFFFF9C93)),
    "file-word-symbol" to FileTypeAsset(R.drawable.file_type_file_word_symbol, Color(0xFF176BFF), Color(0xFF87B6FF)),
    "file-sql-symbol" to FileTypeAsset(R.drawable.file_type_file_sql_symbol, Color(0xFF087D7B), Color(0xFF70DDCE)),
    "file-text" to FileTypeAsset(R.drawable.file_type_file_text, Color(0xFF176BFF), Color(0xFF87B6FF)),
    "file-image" to FileTypeAsset(R.drawable.file_type_file_image, Color(0xFF117BA3), Color(0xFF75D5F6)),
    "file-archive" to FileTypeAsset(R.drawable.file_type_file_archive, Color(0xFFAD7312), Color(0xFFFFD184)),
    "file-code" to FileTypeAsset(R.drawable.file_type_file_code, Color(0xFF087D7B), Color(0xFF70DDCE)),
    "file-config" to FileTypeAsset(R.drawable.file_type_file_config, Color(0xFF536D91), Color(0xFFAAC2E0)),
    "file-table" to FileTypeAsset(R.drawable.file_type_file_table, Color(0xFF16804A), Color(0xFF71DBA1)),
    "file-presentation" to FileTypeAsset(R.drawable.file_type_file_presentation, Color(0xFFC25E12), Color(0xFFFFB76A)),
    "file-audio" to FileTypeAsset(R.drawable.file_type_file_audio, Color(0xFF8054D4), Color(0xFFC1A2FF)),
    "file-video" to FileTypeAsset(R.drawable.file_type_file_video, Color(0xFFB2448A), Color(0xFFF49DCE)),
    "package" to FileTypeAsset(R.drawable.file_type_package, Color(0xFF8054D4), Color(0xFFC1A2FF)),
    "file" to FileTypeAsset(R.drawable.file_type_file, Color(0xFF687386), Color(0xFFB0C0D8)),
    "file-font" to FileTypeAsset(R.drawable.file_type_file_font, Color(0xFF7152BB), Color(0xFFBEA5F2)),
    "file-disk-image" to FileTypeAsset(R.drawable.file_type_file_disk_image, Color(0xFF4868AF), Color(0xFF9EBCFF)),
    "file-design-source" to FileTypeAsset(R.drawable.file_type_file_design_source, Color(0xFFB04479), Color(0xFFF4A3CB)),
    "file-3d" to FileTypeAsset(R.drawable.file_type_file_3d, Color(0xFF07888B), Color(0xFF6DDCE0)),
    "file-certificate" to FileTypeAsset(R.drawable.file_type_file_certificate, Color(0xFFB47B12), Color(0xFFF1CC75)),
)
