<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>BlueLink</AssemblyName>
    <RootNamespace>BlueLink.Launcher</RootNamespace>
    <ApplicationIcon>..\..\design\brand\app-icons\windows\bluelink.ico</ApplicationIcon>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="..\..\design\brand\final\bluelink-final-logo.png">
      <Link>Assets\bluelink-logo.png</Link>
    </Resource>
  </ItemGroup>
</Project>
