"""Generate both clients' file classification and theme resources from the approved catalog.

PNG alpha masks are direct 256 px exports of the Figma masters, not redrawn glyphs.
Run with --check in acceptance to detect stale generated files.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "shared/file-icons/catalog.json"
WIN = ROOT / "windows/BlueLink.App"
ANDROID = ROOT / "android/app/src/main/java/com/bluelink/android"


def generate():
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    icons = catalog["icons"]
    extensions, mimes = {}, {}
    for icon in icons:
        for field, mapping in [("extensions", extensions), ("mimeTypes", mimes)]:
            for key in icon[field]:
                assert key == key.lower() and key not in mapping, f"Duplicate or noncanonical {key}"
                mapping[key] = icon["id"]
        png = ROOT / f"shared/file-icons/res/drawable-nodpi/file_type_{icon['id'].replace('-', '_')}.png"
        assert png.read_bytes()[:8] == b"\x89PNG\r\n\x1a\n", png
    outputs = {}
    cs_map = lambda mapping: "\n".join(f'        ["{k}"] = "{v}",' for k, v in sorted(mapping.items()))
    kt_map = lambda mapping: "\n".join(f'        "{k}" to "{v}",' for k, v in sorted(mapping.items()))
    outputs[WIN / "Files/FileTypeCatalog.g.cs"] = '''// Generated by scripts/generate-file-icons.py. Edit shared/file-icons/catalog.json.
#nullable enable
using System;
using System.Collections.Generic;

namespace BlueLink.Files;

public static class FileTypeCatalog
{
    private static readonly IReadOnlyDictionary<string, string> Extensions = new Dictionary<string, string>
    {
''' + cs_map(extensions) + '''
    };
    private static readonly IReadOnlyDictionary<string, string> MimeTypes = new Dictionary<string, string>
    {
''' + cs_map(mimes) + '''
    };
    public static string Classify(string? name, string? mimeType = null)
    {
        // File names, not the containing directory, determine the extension. No filesystem access.
        var leaf = (name ?? "").Replace('\\\\', '/').Split('/')[^1];
        var dot = leaf.LastIndexOf('.');
        if (dot >= 0 && Extensions.TryGetValue(leaf[(dot + 1)..].ToLowerInvariant(), out var type)) return type;
        var mime = (mimeType ?? "").Split(';')[0].Trim().ToLowerInvariant();
        if (MimeTypes.TryGetValue(mime, out type)) return type;
''' + "\n".join(f'        if (mime.StartsWith("{k}", StringComparison.Ordinal)) return "{v}";' for k, v in catalog["mimePrefixes"].items()) + '''
        return "file";
    }
}
'''
    outputs[ANDROID / "files/FileTypeCatalog.kt"] = '''// Generated by scripts/generate-file-icons.py. Edit shared/file-icons/catalog.json.
package com.bluelink.android.files

import java.util.Locale

internal object FileTypeCatalog {
    private val extensions = mapOf(
''' + kt_map(extensions) + '''
    )
    private val mimeTypes = mapOf(
''' + kt_map(mimes) + '''
    )
    fun classify(name: String?, mimeType: String? = null): String {
        val leaf = (name ?: "").replace('\\\\', '/').substringAfterLast('/')
        extensions[leaf.substringAfterLast('.', "").lowercase(Locale.ROOT)]?.let { return it }
        val mime = (mimeType ?: "").substringBefore(';').trim().lowercase(Locale.ROOT)
        mimeTypes[mime]?.let { return it }
''' + "\n".join(f'        if (mime.startsWith("{k}")) return "{v}"' for k, v in catalog["mimePrefixes"].items()) + '''
        return "file"
    }
}
'''
    outputs[ANDROID / "ui/content/FileTypeAssets.kt"] = '''// Generated by scripts/generate-file-icons.py. Edit shared/file-icons/catalog.json.
package com.bluelink.android.ui.content

import androidx.compose.ui.graphics.Color
import com.bluelink.android.R

internal data class FileTypeAsset(val drawable: Int, val light: Color, val dark: Color)
internal val fileTypeAssets = mapOf(
''' + "\n".join(f'    "{i["id"]}" to FileTypeAsset(R.drawable.file_type_{i["id"].replace("-", "_")}, Color(0xFF{i["light"][1:]}), Color(0xFF{i["dark"][1:]})),' for i in icons) + "\n)\n"
    xaml = ['<!-- Generated by scripts/generate-file-icons.py. -->', '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">']
    for i in icons:
        xaml.append(f'''    <DrawingImage x:Key="FileTypeIcon-{i['id']}">
        <DrawingImage.Drawing>
            <DrawingGroup RenderOptions.BitmapScalingMode="HighQuality">
                <DrawingGroup.OpacityMask>
                    <ImageBrush ImageSource="/BlueLink;component/Assets/FileTypes/file_type_{i['id'].replace('-', '_')}.png" Stretch="Fill"/>
                </DrawingGroup.OpacityMask>
                <GeometryDrawing Brush="{{DynamicResource FileTypeBrush-{i['id']}}}">
                    <GeometryDrawing.Geometry><RectangleGeometry Rect="0,0,256,256"/></GeometryDrawing.Geometry>
                </GeometryDrawing>
            </DrawingGroup>
        </DrawingImage.Drawing>
    </DrawingImage>''')
    outputs[WIN / "Themes/FileTypes.xaml"] = "\n".join(xaml + ["</ResourceDictionary>", ""])
    for theme in ["Light", "Dark"]:
        path = WIN / f"Themes/Palette.{theme}.xaml"
        text = path.read_text(encoding="utf-8-sig")
        start = "    <!-- Generated file type colors: start -->"
        end = "    <!-- Generated file type colors: end -->"
        block = "\n".join([start] + [f'    <SolidColorBrush x:Key="FileTypeBrush-{i["id"]}" Color="{i[theme.lower()]}"/>' for i in icons] + [end])
        if start in text:
            before, rest = text.split(start, 1)
            _, after = rest.split(end, 1)
            text = before + block + after
        else:
            text = text.replace("</ResourceDictionary>", block + "\n</ResourceDictionary>")
        outputs[path] = text
    return outputs


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, expected in generate().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8-sig") != expected:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Stale generated file icon resources: " + ", ".join(stale))
    print("File icon catalog: 19 categories; both platform resources " + ("verified" if args.check else "generated"))
